server:
  port: 8081
spring:
  application:
    name: product
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/product?useSSL=false&serverTimezone=UTC
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/